### ISSUE TITLE
global command error in non-git-repo dir

### ISSUE THREAD

**Issue by hotoo** [hotoo/gitopen#12]
```
$ cd ~
$ gitopen @hotoo/gitopen
child_process.js:475
    throw err;
          ^
Error: Command failed: git config remote.origin.url

    at checkExecSyncError (child_process.js:432:13)
    at Object.execSync (child_process.js:472:13)
    at Object.getRemoteUrl (/usr/local/lib/node_modules/gitopen/lib/gitremote.js:10:27)
    at Object.<anonymous> (/usr/local/lib/node_modules/gitopen/bin/gitopen:8:21)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:117:18)
```

**Comment by hotoo** [comment]
Failed Bug Report in 1.2.1
