### ISSUE TITLE
Breaks with node v6

### ISSUE THREAD

**Issue by dferber90** [hotoo/gitopen#40]
`gitopen` stopped working after I upgraded to node v6. I saw the same thing happen to a colleague.

Is this a known problem?

<details>
<summary>Log</summary>
```
$ node -v
v6.9.1
$ npm -v
3.10.8
$ gitopen
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at module.exports (/Users/nick/npm-global/lib/node_modules/gitopen/bin/open-commander.js:86:15)
    at Object.<anonymous> (/Users/nick/npm-global/lib/node_modules/gitopen/bin/gitopen:15:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
$ gitopen pr
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at module.exports (/Users/nick/npm-global/lib/node_modules/gitopen/bin/open-commander.js:86:15)
    at Object.<anonymous> (/Users/nick/npm-global/lib/node_modules/gitopen/bin/gitopen:15:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```
</details>

*Problem*
The problem appears because we're calling `path.dirname` with `undefined` (`commander.path`).
This seems to fix the issue:

```diff
- cwd: path.dirname(commander.path) || option.cwd || process.cwd(),
+ cwd: commander.path ? path.dirname(commander.path) : (option.cwd || process.cwd()),
```
in https://github.com/hotoo/gitopen/blob/d42851b/bin/open-commander.js#L86

**Comment by hotoo** [comment]
2.5.1
