### ISSUE TITLE
Error: Command failed: git config --list --local | grep "^gitopen\."

### ISSUE THREAD

**Issue by pityonline** [hotoo/gitopen#73]
Hi, hooto:

Thanks for this convenient tool. I found an update to 3.0.0 today and I upgraded it, but I got an error:

```
child_process.js:679
    throw err;
    ^

Error: Command failed: git config --list --global | grep "^gitopen\.gitlab\.company\.com\."
    at checkExecSyncError (child_process.js:639:11)
    at Object.execSync (child_process.js:676:15)
    at openrc (/usr/local/lib/node_modules/gitopen/bin/openrc.js:59:17)
    at /usr/local/lib/node_modules/gitopen/bin/gitopen:60:16
    at module.exports (/usr/local/lib/node_modules/gitopen/bin/open-commander.js:335:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/gitopen/bin/gitopen:16:1)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
```

I found that I need to add some config into `~/.gitconfig` now because I'm using GitLab CE. So I added:

```
[gitopen "gitlab.company.com"]
    type = gitlab
    protocol = https
```

Now it reports:

```
child_process.js:679
    throw err;
    ^

Error: Command failed: git config --list --local | grep "^gitopen\."
    at checkExecSyncError (child_process.js:639:11)
    at Object.execSync (child_process.js:676:15)
    at openrc (/usr/local/lib/node_modules/gitopen/bin/openrc.js:71:17)
    at /usr/local/lib/node_modules/gitopen/bin/gitopen:60:16
    at module.exports (/usr/local/lib/node_modules/gitopen/bin/open-commander.js:335:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/gitopen/bin/gitopen:16:1)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
```

I wonder why it looks for the local config after I added the configuration into the global `~/.gitconfig`. Could you take a look at it?

My ~/.gitopenrc:

```
gitlab.company.com:
    type: gitlab
    protocol: https
```

**Comment by hotoo** [comment]
Is my problem, I will fix it immediately.

**Comment by pityonline** [comment]
It's working now. Thanks!
